### ISSUE TITLE
Possible to whitelist trains?

### ISSUE THREAD

**Issue by jamesrchen** [PhaserArray/AutoVehicleClear#1]
Trains and so have been a problem since when you clear it, it will leave certain parts on the track.

**Comment by jamesrchen** [comment]
*you

**Comment by PhaserArray** [comment]
From my testing when I made this plugin, trains seemed to be ignored completely. Nevertheless, I added an explicit check to make sure trains don't get deleted. There's a [new release](https://github.com/PhaserArray/AutoVehicleClear/releases/tag/v1.1) out, let me know if you notice any other issues with it.
